name: Deploy WebApp (Staging Env)

on:
  push:
    branches: [main]

env:
  PNPM_CACHE_FOLDER: .pnpm-store

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: setup caching
        uses: actions/cache@v2
        with:
          path: ${{ env.PNPM_CACHE_FOLDER }}
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: install pnpm
        uses: pnpm/action-setup@v1.2.1
        with:
          version: 5.17.2

      - name: setup pnpm config
        run: pnpm config set store-dir $PNPM_CACHE_FOLDER

      - name: install dependencies
        run: pnpm install

      - name: lint js
        run: pnpm lint:script

      - name: lint style
        run: pnpm lint:style
      
      - name: format js
        run: pnpm format:script

      - name: format style
        run: pnpm format:style
      
      - name: build
        run: pnpm build
  
  deploy:
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
      - name: SSH and deploy node app
        uses: appleboy/ssh-action@master
        with:
          host: '${{ secrets.SSH_HOST }}'
          username: '${{ secrets.SSH_USERNAME }}'
          key: '${{ secrets.SSH_KEY }}'
          port: '${{ secrets.SSH_PORT }}'
          script: |
            cd ~/apps/project-management
            git checkout --f main
            git remote prune origin
            git pull
            docker-compose -f docker-compose.yml up -d --no-deps --build pms-web-app